[package]
name = "credibil-jose"
description = "Credibil information security utilities for Javascript Object Signing and Encryption (JOSE) and JSON Web Tokens (JWT)."
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Credibil"]
categories = ["cryptography"]
edition = "2024"
exclude = [".*", "snapshots/"]
homepage = "https://credibil.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
repository = "https://github.com/credibil/jose"
rust-version = "1.86"
version = "0.1.2"

[lib]
# crate-type = ["cdylib", "rlib"]

[lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[dependencies]
anyhow = "1.0.98"
base64ct = { version = "1.7.3", features = ["std"] }
# credibil-ose = { git = "https://github.com/credibil/ose.git" }
credibil-ose = { path = "../ose" }
ecdsa = "0.16.9"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
k256 = "0.13.4"
multibase = "0.9.1"
rand = "0.8.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
serde_repr = "0.1"
tracing = "0.1.41"
zeroize = "1.8.1"

[dev-dependencies]
hex = "0.4.3"
signature = "2.2.0"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
test-kms = { path = "../ose/crates/test-kms" }
# test-kms = { git = "https://github.com/credibil/ose.git" }
